language: java
jdk:
  - openjdk8

# CI를 어떤 브랜치에서 푸시될 때 수행할지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home

# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 이메일 알람
notifications:
  email:
    recipients:
      - jhm0828@gmail.com